server.port=8083

server.servlet.context-path=/kitchensink

management.endpoints.web.exposure.include=*
management.prometheus.metrics.export.enabled=true
management.endpoint.prometheus.access=read_only

#spring.data.mongodb.uri=mongodb+srv://root:2nXsoaNi43EsPxgz@cluster0.agems.mongodb.net/memberdb